### ISSUE TITLE
How to show large amounts of videos?

### ISSUE THREAD

**Issue by kodbilenadam** [the-machine-project/the-machine#11]
What should i do for them? There will be lots of videos on the main screen. What should I use to show them in one page without lagging?

**Comment by devloop0** [comment]
Yeah, a host with a lot of processing power and bandwidth will be needed. However, I think we should change the milestone (Day 1)? It doesn't seem to be a feasible milestone as of now.

**Comment by devloop0** [comment]
This doesn't seem like something that could feasibly be achieved for the Day 0 milestone so I changed it to Day 1.

**Comment by Xalaxis** [comment]
I think at this stage, it's probably looking like we'll have a single video, with lots of individual videos as part of it.  I had a good example of this and will go looking for it again at some point. - Will link here if found.

**Comment by kodbilenadam** [comment]
Solution found: WebM

**Comment by Xalaxis** [comment]
@kodbilenadam If you're still unsure, look at how 'beyond recollection' handles it's videos.

**Comment by Xalaxis** [comment]
@kodbilenadam (Sorry, 'because recollection') [here](http://www.because-recollection.com/)
