### ISSUE TITLE
Submitting Code to be validated

### ISSUE THREAD

**Issue by gateslm** [the-machine-project/the-machine#25]
I submitted an issue earlier about the developer version having an error because the openCv file does not exist. I am not an expert at Github, how can push changes to a branch to show a fix that might work?

**Comment by devloop0** [comment]
Try submitting a pull request, we'll approve it if it solves a problem or adds a feature.

**Comment by gateslm** [comment]
I get "It seems you do not have permission to push your changes to this repository."

**Comment by Jaloko** [comment]
You will need to fork the repository first unless you are added as a contributor to this one.

**Comment by devloop0** [comment]
This is correct. Fork the repository and then there should be an option to submit a pull request. Here is a link that can help you get started. https://help.github.com/articles/using-pull-requests/#initiating-the-pull-request

**Comment by Xalaxis** [comment]
If that's all clear I'm going to go ahead and close this issue.
