### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by evilpig** [the-machine-project/the-machine#30]
I tried to download this program but have been having some issues. I've downloaded both the x86 and x64 versions. I am on Windows x64 but that version doesn't open at all. I've tried the x86 version but I get to the point where it asks my name then just goes black and nothing happens. I've updated my java as well. I am on Windows 10

edit: After closing and opening it a few times I eventually saw my face. It said training and once it got to 200 it froze and I had to force close it.

**Comment by devloop0** [comment]
After it gets to 200 samples, it begins to train itself to recognize your face.
It freezes (should take no longer than a minute), then the machine closes. You restart it and it will recognize you as admin. Try running the whole thing again, but be sure to delete the FACIAL_DATA directory, the TRAINING directory, and the IDENTITY_DATABASE.db files and re-running it. If it continues to crash, open command prompt and cd to the MACHINE directory and run java -jar machine.jar and let me know what the output is when it crashes.
Also, every time it does crash, be sure to delete the 3 things that I mentioned.

**Comment by evilpig** [comment]
I tried that and it worked this time. It closed pretty quickly then reopened it and all was good.

**Comment by devloop0** [comment]
So can I close this issue?

**Comment by Xalaxis** [comment]
Closing issue unless there are continuing problems.
