### ISSUE TITLE
Manual Composition 

### ISSUE THREAD

**Issue by PrimaryAsset** [the-machine-project/the-machine#40]
How do i compile the machine manually?

**Comment by devloop0** [comment]
The instructions for compiling the machine from source are in the README.md file which is rendered when you go to our repo on a web browser. Are you stuck on a specific step?

**Comment by PrimaryAsset** [comment]
No i just was having the issue addressed in #34 And didnt know where to find the instructions.

**Comment by devloop0** [comment]
Yeah, to open the terminal, you need to press ctrl + alt + T. Is there any other problem or can I close this issue?

**Comment by PrimaryAsset** [comment]
Nope im good! 👍🏻
