### ISSUE TITLE
Microphone Handler Startup Issue

### ISSUE THREAD

**Issue by PrimaryAsset** [the-machine-project/the-machine#41]
When starting up the machine i get 8 Errors and i dont know how to fix them. The Error message is as follows.

Information:Using javac 1.8.0_91 to compile java sources
Information:java: Errors occurred while compiling module 'machine'
Information:6/15/2016 5:28 PM - Compilation completed with 8 errors and 1 warning in 2s 19ms
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\MicrophoneHandler.java
    Error:Error:line (3)java: package edu.cmu.sphinx.api does not exist
    Error:Error:line (4)java: package edu.cmu.sphinx.api does not exist
    Error:Error:line (5)java: package edu.cmu.sphinx.api does not exist
    Error:Error:line (24)java: cannot find symbol
  symbol:   class LiveSpeechRecognizer
  location: class org.themachineproject.machine.MicrophoneHandler
    Error:Error:line (43)java: cannot find symbol
  symbol:   class Configuration
  location: class org.themachineproject.machine.MicrophoneHandler
    Error:Error:line (43)java: cannot find symbol
  symbol:   class Configuration
  location: class org.themachineproject.machine.MicrophoneHandler
    Error:Error:line (48)java: cannot find symbol
  symbol:   class LiveSpeechRecognizer
  location: class org.themachineproject.machine.MicrophoneHandler
    Error:Error:line (62)java: cannot find symbol
  symbol:   class SpeechResult
  location: class org.themachineproject.machine.MicrophoneHandler
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\FacialRecognition.java
    Warning:Warning:line (132)java: getIntBuffer() in org.bytedeco.javacpp.helper.opencv_core.AbstractArray has been deprecated

**Comment by devloop0** [comment]
Try this: http://stackoverflow.com/questions/9980869/force-intellij-idea-to-reread-all-maven-dependencies, it doesn't seem to be pulling the CMU Sphinx dependency.

**Comment by PrimaryAsset** [comment]
That fixed that problem but now i have this




Information:Using javac 1.8.0_91 to compile java sources
Information:java: Errors occurred while compiling module 'machine'
Information:Module "machine" was fully rebuilt due to project configuration/dependencies changes
Information:6/15/2016 5:43 PM - Compilation completed with 27 errors and 3 warnings in 1s 812ms
Warning:java: source value 1.5 is obsolete and will be removed in a future release
Warning:java: target value 1.5 is obsolete and will be removed in a future release
Warning:java: To suppress warnings about obsolete options, use -Xlint:-options.
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\DispatchTable.java
    Error:Error:line (14)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\IdentityDataBaseFile.java
    Error:Error:line (88)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
    Error:Error:line (93)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\FacialDetection.java
    Error:Error:line (110)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\KillAllCommand.java
    Error:Error:line (21)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\AddUserCommand.java
    Error:Error:line (19)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\ResetCommand.java
    Error:Error:line (23)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\WebcamHandler.java
    Error:Error:line (83)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
    Error:Error:line (93)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\ChPermCommand.java
    Error:Error:line (18)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\IdentityEntry.java
    Error:Error:line (91)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\ExitCommand.java
    Error:Error:line (21)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\UserPlatform.java
    Error:Error:line (28)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\FacialRecognition.java
    Error:Error:line (73)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
    Error:Error:line (123)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\Terminal.java
    Error:Error:line (53)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\RmUserCommand.java
    Error:Error:line (26)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\Assets.java
    Error:Error:line (81)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
    Error:Error:line (147)java: multi-catch statement is not supported in -source 1.5
  (use -source 7 or higher to enable multi-catch statement)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\StartUpAnimation.java
    Error:Error:line (233)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\SelectWebcam.java
    Error:Error:line (43)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\LsUserCommand.java
    Error:Error:line (23)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
    Error:Error:line (32)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\ClearCommand.java
    Error:Error:line (21)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\MicrophoneHandler.java
    Error:Error:line (30)java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\HelpCommand.java
    Error:Error:line (22)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
C:\Users\Richard\Desktop\the-machine-master (1)\the-machine-master\src\main\java\org\themachineproject\machine\command\RetrainCommand.java
    Error:Error:line (22)java: diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)

**Comment by devloop0** [comment]
I suggest Googling compilation errors, but you need to change the bytecode level and the java compiler level used in project settings, project dependencies, and general settings.

**Comment by devloop0** [comment]
These need to be at 1.8 or Java 8.

**Comment by PrimaryAsset** [comment]
There is also an error in the top right that says

"Invalid VCS root mapping the directory <PROJECT> is registered as a Git root, but no git repositories were found there"

**Comment by PrimaryAsset** [comment]
All good now thanks!
